### ISSUE TITLE
errors from abaplint 2.93.46

### ISSUE THREAD

**Issue by larshp** [Marc-Bernard-Tools/MBT-Listcube#1]
abaplint 2.93.46 will introduce these new findings, which looks correct?

also https://github.com/Marc-Bernard-Tools/MBT-Listcube/blob/main/abaplint.json#L303 so I guess you dont want to use these variables?

* [MBT-Listcube/src/#mbtools#bw_listcube.fugr.#mbtools#bw_view_infoprov.abap:101](https://github.com/Marc-Bernard-Tools/MBT-Listcube/blob/main/src/%23mbtools%23bw_listcube.fugr.%23mbtools%23bw_view_infoprov.abap#L101): "rs_c_true" not found, findTop(check_syntax)

* [MBT-Listcube/src/#mbtools#bw_listcube.fugr.#mbtools#bw_view_infoprov.abap:113](https://github.com/Marc-Bernard-Tools/MBT-Listcube/blob/main/src/%23mbtools%23bw_listcube.fugr.%23mbtools%23bw_view_infoprov.abap#L113): "rs_c_true" not found, findTop(check_syntax)

**Comment by mbtools** [comment]
thanks. sticking with `abap_true/false` 😄
