### ISSUE TITLE
bw_view_infoprov, abaplint regression

### ISSUE THREAD

**Issue by larshp** [Marc-Bernard-Tools/MBT-Listcube#2]
Hi,
The latest abaplint will report a https://rules.abaplint.org/definitions_top/ problem in https://github.com/Marc-Bernard-Tools/MBT-Listcube/blob/main/src/%23mbtools%23bw_listcube.fugr.%23mbtools%23bw_view_infoprov.abap#L48

exclude or change the code

**Comment by mbtools** [comment]
moved to top https://github.com/Marc-Bernard-Tools/MBT-Listcube/commit/3951b79d2e32857dafaf04a6446ee28b3a323ce8
